// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Migrasi butuh koneksi langsung (non-pooled) ke Postgres. Kalau pakai
    // Supabase, DATABASE_URL diisi connection string pooled (PgBouncer) untuk
    // runtime app, sementara DIRECT_URL diisi direct connection khusus migrasi.
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
